#!/bin/bash
set -eou pipefail

CYAN='\033[0;36m'
NC='\033[0m' # No Color

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

#shellcheck disable=SC1091,SC1090
. "$dir/env.sh"

#shellcheck disable=SC2154
var_ctl_repo="$ctl_repo"
#shellcheck disable=SC2154
var_env_repo="$env_repo"

if [ ! -d "$dir/ctl/.git" ] || [ "${1:-}" = "-f" ]; then
	echo -e "${CYAN}$(date '+%F %X') Clone the controller repository...${NC}"
	shopt -s dotglob && rm -rf "$dir/ctl"/*
	git clone "$var_ctl_repo" "$dir/ctl"
else
	echo -e "${CYAN}$(date '+%F %X') Pull the controller repository...${NC}"
	git -C "$dir/ctl" pull
fi

echo -e "${CYAN}$(date '+%F %X') [start] Controller Setup...${NC}"

"$dir/ctl/run" setup "$var_env_repo"

echo -e "${CYAN}$(date '+%F %X') [end] Controller Setup${NC}"